# Generated by Django 4.2.30 on 2026-07-03 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_enable_rls'),
        ('bootstrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbinding',
            name='provider',
            field=models.CharField(choices=[('gmail_oauth', 'Gmail OAuth'), ('imap_smtp', 'IMAP/SMTP')], max_length=16),
        ),
        migrations.AlterField(
            model_name='systemagent',
            name='status',
            field=models.CharField(choices=[('shadow', 'Shadow'), ('active', 'Active')], default='shadow', max_length=16),
        ),
        migrations.AlterField(
            model_name='tenantbootstrapprogress',
            name='tenant',
            field=models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bootstrap_progress', serialize=False, to='tenants.tenant'),
        ),
    ]
