"""Workspace brief generator for E4-1.

A brief is a cold, INDEX-only cache that answers "what is in this workspace?"
without scanning content at request time. It is regenerated by the ambient cycle
and never produced inline by an endpoint.
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from typing import Any

from ..context import Context
from ..db import new_id, utc_now
from ..db_adapter import transaction
from ..key_broker import KeyLevel, resolve_read_level


DEFAULT_STALENESS = {"max_age_h": 24, "max_writes": 50}


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _hours_ago(hours: int) -> str:
    return (_now() - timedelta(hours=hours)).isoformat(timespec="milliseconds").replace("+00:00", "Z")


def _fmt_dt(dt: datetime) -> str:
    return dt.isoformat(timespec="milliseconds").replace("+00:00", "Z")


def _user_roles(ctx: Context) -> set[str]:
    roles: set[str] = set()
    if ctx.actor_role_at_decision:
        roles.add(ctx.actor_role_at_decision.lower())
    return roles


def _count_recent_writes(conn: Any, ctx: Context, workspace_id: str, since: str) -> int:
    """Cheap write counter from usage_record since the last brief computation."""

    with transaction(conn, ctx=ctx):
        row = conn.execute(
            """
            SELECT COUNT(*) AS n
            FROM usage_record
            WHERE workspace_id = ? AND tenant_id = ? AND created_at > ?
            """,
            (workspace_id, ctx.require_tenant(), since),
        ).fetchone()
    return int(row["n"] if row else 0)


def _source_counts(conn: Any, ctx: Context, workspace_id: str) -> dict[str, int]:
    with transaction(conn, ctx=ctx):
        rows = conn.execute(
            """
            SELECT type, COUNT(*) AS n
            FROM kb_source
            WHERE workspace_id = ? AND tenant_id = ?
            GROUP BY type
            """,
            (workspace_id, ctx.require_tenant()),
        ).fetchall()
    return {row["type"]: int(row["n"]) for row in rows}


def _recent_titles(conn: Any, ctx: Context, workspace_id: str, limit: int) -> list[dict[str, Any]]:
    """Return recent source titles only (INDEX-level pointer, never content)."""

    with transaction(conn, ctx=ctx):
        rows = conn.execute(
            """
            SELECT id, type, title, created_at
            FROM kb_source
            WHERE workspace_id = ? AND tenant_id = ?
            ORDER BY created_at DESC
            LIMIT ?
            """,
            (workspace_id, ctx.require_tenant(), limit),
        ).fetchall()
    return [
        {"id": row["id"], "type": row["type"], "title": row["title"], "created_at": row["created_at"]}
        for row in rows
    ]


def _open_invoices(conn: Any, ctx: Context, workspace_id: str) -> dict[str, Any]:
    """Return aggregated open-invoice data only; no item details are persisted."""

    # manual_invoice is tenant-scoped (no workspace_id column in v37 schema).
    with transaction(conn, ctx=ctx):
        rows = conn.execute(
            """
            SELECT total
            FROM manual_invoice
            WHERE tenant_id = ? AND status IN ('draft', 'sent')
            ORDER BY created_at DESC
            LIMIT 50
            """,
            (ctx.require_tenant(),),
        ).fetchall()
    total = sum(float(row["total"] or 0.0) for row in rows)
    return {
        "count": len(rows),
        "total_usd": round(total, 4),
    }


def _active_routines(conn: Any, ctx: Context, workspace_id: str) -> list[dict[str, Any]]:
    with transaction(conn, ctx=ctx):
        rows = conn.execute(
            """
            SELECT id, name, created_at
            FROM routine
            WHERE workspace_id = ? AND tenant_id = ? AND is_active = 1
            ORDER BY updated_at DESC
            LIMIT 20
            """,
            (workspace_id, ctx.require_tenant()),
        ).fetchall()
    return [
        {"id": row["id"], "name": row["name"], "created_at": row["created_at"]}
        for row in rows
    ]


def _last_routine_run(conn: Any, ctx: Context, workspace_id: str) -> dict[str, Any] | None:
    with transaction(conn, ctx=ctx):
        row = conn.execute(
            """
            SELECT id, routine_id, status, created_at
            FROM routine_run
            WHERE workspace_id = ? AND tenant_id = ?
            ORDER BY created_at DESC
            LIMIT 1
            """,
            (workspace_id, ctx.require_tenant()),
        ).fetchone()
    if row is None:
        return None
    return {
        "id": row["id"],
        "routine_id": row["routine_id"],
        "status": row["status"],
        "created_at": row["created_at"],
    }


def _recent_activity(conn: Any, ctx: Context, workspace_id: str, limit: int) -> list[dict[str, Any]]:
    """Recent audit-like events: usage records as cheap activity proxy."""

    with transaction(conn, ctx=ctx):
        rows = conn.execute(
            """
            SELECT id, capability, model, cost_usd, created_at
            FROM usage_record
            WHERE workspace_id = ? AND tenant_id = ?
            ORDER BY created_at DESC
            LIMIT ?
            """,
            (workspace_id, ctx.require_tenant(), limit),
        ).fetchall()
    return [
        {
            "id": row["id"],
            "type": "usage",
            "capability": row["capability"],
            "model": row["model"],
            "cost_usd": float(row["cost_usd"] or 0.0),
            "created_at": row["created_at"],
        }
        for row in rows
    ]


def _extract_entities(titles: list[dict[str, Any]]) -> list[str]:
    """Very cheap entity extraction from titles only (no LLM, no content)."""

    entities: set[str] = set()
    for item in titles:
        title = (item.get("title") or "").lower()
        # Simple heuristic: capitalized words or quoted phrases.
        for word in title.split():
            if len(word) > 3 and word[0].isupper():
                entities.add(word.strip(".,;:!?\"'"))
    return sorted(entities)[:20]


def build_workspace_brief(
    ctx: Context,
    conn: Any,
    workspace_id: str,
    *,
    cost_usd: float = 0.0,
) -> dict[str, Any]:
    """Build an INDEX-only brief for a workspace.

    The generator consults the key broker before reading anything. CLOSED spaces
    produce a sealed brief. CONTENT spaces expose only INDEX-level pointers for
    non-approvers. CEO-only spaces are never included.
    """

    tenant_id = ctx.require_tenant()
    roles = _user_roles(ctx)

    level, sealed = resolve_read_level(
        conn,
        tenant_id=tenant_id,
        space_id=workspace_id,
        user_roles=roles,
        default=KeyLevel.INDEX,
    )

    # Cache the maximum CONTENT aggregates the workspace policy allows for its
    # approvers. The ambient cycle runs with role ``system`` and would otherwise
    # never persist invoice aggregates; the GET endpoint re-mediates them by
    # the requester's actual roles, so non-approvers still never see them.
    max_level, _ = resolve_read_level(
        conn,
        tenant_id=tenant_id,
        space_id=workspace_id,
        user_roles={"owner", "curator", "ceo"},
        default=KeyLevel.INDEX,
    )

    if level == KeyLevel.CLOSED:
        source_counts = _source_counts(conn, ctx, workspace_id)
        return {
            "sealed": True,
            "object_count": sum(source_counts.values()),
            "level": "closed",
            "source_counts": source_counts,
        }

    # INDEX level: counts, titles, routines, activity. CONTENT adds invoice aggregates.
    source_counts = _source_counts(conn, ctx, workspace_id)
    recent_titles = _recent_titles(conn, ctx, workspace_id, limit=10)
    entities = _extract_entities(recent_titles)
    active_routines = _active_routines(conn, ctx, workspace_id)
    last_run = _last_routine_run(conn, ctx, workspace_id)
    activity = _recent_activity(conn, ctx, workspace_id, limit=10)

    brief: dict[str, Any] = {
        "sealed": sealed,
        "level": level.value,
        "source_counts": source_counts,
        "recent_titles": [{"id": t["id"], "type": t["type"], "title": t["title"]} for t in recent_titles],
        "frequent_entities": entities,
        "active_routines": active_routines,
        "last_routine_run": last_run,
        "recent_activity": activity,
    }
    if max_level == KeyLevel.CONTENT:
        brief["open_invoices"] = _open_invoices(conn, ctx, workspace_id)

    return brief


def is_brief_stale(
    conn: Any,
    ctx: Context,
    workspace_id: str,
    policy: dict[str, Any] | None = None,
) -> tuple[bool, dict[str, Any]]:
    """Return (stale, diagnostics) for a workspace brief."""

    policy = policy or DEFAULT_STALENESS
    max_age_h = int(policy.get("max_age_h", DEFAULT_STALENESS["max_age_h"]))
    max_writes = int(policy.get("max_writes", DEFAULT_STALENESS["max_writes"]))

    with transaction(conn, ctx=ctx):
        row = conn.execute(
            """
            SELECT computed_at, staleness_policy_json, version
            FROM workspace_brief
            WHERE tenant_id = ? AND workspace_id = ?
            """,
            (ctx.require_tenant(), workspace_id),
        ).fetchone()

    if row is None or row["computed_at"] is None:
        return True, {"reason": "missing", "writes_since": 0}

    computed_at = datetime.fromisoformat(row["computed_at"].replace("Z", "+00:00"))
    age_hours = (_now() - computed_at).total_seconds() / 3600
    writes_since = _count_recent_writes(conn, ctx, workspace_id, row["computed_at"])

    diagnostics = {
        "age_hours": round(age_hours, 2),
        "max_age_h": max_age_h,
        "writes_since": writes_since,
        "max_writes": max_writes,
        "version": row["version"],
    }

    if age_hours > max_age_h:
        return True, {**diagnostics, "reason": "age"}
    if writes_since > max_writes:
        return True, {**diagnostics, "reason": "writes"}
    return False, {**diagnostics, "reason": "fresh"}


def refresh_workspace_brief(
    ctx: Context,
    conn: Any,
    workspace_id: str,
    *,
    cost_usd: float = 0.0,
    policy: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Regenerate and persist the brief for a workspace. Returns the row."""

    policy = policy or DEFAULT_STALENESS
    brief = build_workspace_brief(ctx, conn, workspace_id, cost_usd=cost_usd)

    source_counts = brief.get("source_counts", {})
    now = utc_now()
    actor_id = ctx.actor_id or ctx.user_id or "system"
    actor_role = ctx.actor_role_at_decision or "system"

    with transaction(conn, ctx=ctx):
        existing = conn.execute(
            """
            SELECT version FROM workspace_brief
            WHERE tenant_id = ? AND workspace_id = ?
            """,
            (ctx.require_tenant(), workspace_id),
        ).fetchone()

        version = int(existing["version"] if existing else 0) + 1
        conn.execute(
            """
            INSERT INTO workspace_brief (
                tenant_id, workspace_id, brief_json, computed_at,
                source_counts_json, staleness_policy_json, generation_cost_usd, version,
                actor_id, actor_role_at_decision, routine_version, skill_version,
                schema_version, source_version, approved_by, created_at, updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(tenant_id, workspace_id) DO UPDATE SET
                brief_json = excluded.brief_json,
                computed_at = excluded.computed_at,
                source_counts_json = excluded.source_counts_json,
                staleness_policy_json = excluded.staleness_policy_json,
                generation_cost_usd = excluded.generation_cost_usd,
                version = excluded.version,
                actor_id = excluded.actor_id,
                actor_role_at_decision = excluded.actor_role_at_decision,
                schema_version = excluded.schema_version,
                source_version = excluded.source_version,
                approved_by = excluded.approved_by,
                updated_at = excluded.updated_at
            """,
            (
                ctx.require_tenant(),
                workspace_id,
                json.dumps(brief, ensure_ascii=False),
                now,
                json.dumps(source_counts, ensure_ascii=False),
                json.dumps(policy, ensure_ascii=False),
                cost_usd,
                version,
                actor_id,
                actor_role,
                None,
                None,
                42,
                "v1",
                None,
                now,
                now,
            ),
        )
        row = conn.execute(
            """
            SELECT * FROM workspace_brief
            WHERE tenant_id = ? AND workspace_id = ?
            """,
            (ctx.require_tenant(), workspace_id),
        ).fetchone()

    return dict(row)


def get_workspace_brief(
    conn: Any,
    ctx: Context,
    workspace_id: str,
) -> dict[str, Any] | None:
    """Return the persisted brief row, or None if missing."""

    with transaction(conn, ctx=ctx):
        row = conn.execute(
            """
            SELECT * FROM workspace_brief
            WHERE tenant_id = ? AND workspace_id = ?
            """,
            (ctx.require_tenant(), workspace_id),
        ).fetchone()
    if row is None:
        return None
    data = dict(row)
    data["brief"] = json.loads(data.get("brief_json") or "{}")
    data["source_counts"] = json.loads(data.get("source_counts_json") or "{}")
    data["staleness_policy"] = json.loads(data.get("staleness_policy_json") or "{}")
    return data


def list_workspace_briefs(
    conn: Any,
    ctx: Context,
    workspace_ids: list[str] | None = None,
) -> list[dict[str, Any]]:
    """List briefs for workspaces visible in the current context."""

    tenant_id = ctx.require_tenant()
    with transaction(conn, ctx=ctx):
        if workspace_ids:
            placeholders = ",".join("?" * len(workspace_ids))
            rows = conn.execute(
                f"""
                SELECT * FROM workspace_brief
                WHERE tenant_id = ? AND workspace_id IN ({placeholders})
                """,
                (tenant_id, *workspace_ids),
            ).fetchall()
        else:
            rows = conn.execute(
                """
                SELECT * FROM workspace_brief
                WHERE tenant_id = ?
                """,
                (tenant_id,),
            ).fetchall()

    result = []
    for row in rows:
        data = dict(row)
        data["brief"] = json.loads(data.get("brief_json") or "{}")
        data["source_counts"] = json.loads(data.get("source_counts_json") or "{}")
        data["staleness_policy"] = json.loads(data.get("staleness_policy_json") or "{}")
        result.append(data)
    return result
