"""Shared constants for the living agent / autonomy subsystem (E4)."""

# Track-record thresholds used by the model catalog scoring logic.
TRACK_RECORD_ACCEPTANCE_BONUS_THRESHOLD = 0.90
TRACK_RECORD_FILTER_THRESHOLD = 0.70
TRACK_RECORD_FILTER_MIN_SAMPLES = 20

# ACE promotion/degradation thresholds.
ACE_MIN_SHADOW_DECISIONS_FOR_PROMOTION = 50
ACE_COOLDOWN_DAYS_AFTER_DOUBLE_DEGRADATION = 30
ACE_DEGRADE_WINDOW_HOURS = 24
ACE_DEGRADE_OVERRUN_RATIO = 1.5
ACE_ABSURD_COST_RATIO = 1.5
ACE_DEFAULT_REPORT_DAYS = 14

# E4-4 — Presencia única
DEFAULT_AGENT_DISPLAY_NAME = "Faber"

# E4-5 — Personal memory (CAPA 1)
MEMORY_NAMESPACE_PREFIX = "living_agent"
MEMORY_DEFAULT_AGENT_SLUG = "default"
MEMORY_KIND_PREFERENCE = "preference"
MEMORY_KIND_FACT = "fact"
MEMORY_PATTERN_THRESHOLD_DEFAULT = 3
MEMORY_DETECTOR_LOOKBACK_DAYS = 14
MEMORY_NOTIFICATION_CADENCE_DAYS = 7
MEMORY_MAX_CANDIDATES_PER_CYCLE = 10
MEMORY_INJECTION_MAX_TOKENS = 2000
MEMORY_INJECTION_TOP_K = 5
MEMORY_UNCONSOLIDATED_HOT = 6
MEMORY_UNCONSOLIDATED_WARM = 3
