# Generated by Django 4.2.30 on 2026-07-03 01:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_enable_rls'),
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=255)),
                ('invocation_mode', models.CharField(choices=[('ad_hoc', 'Ad hoc'), ('scheduled', 'Scheduled'), ('webhook', 'Webhook'), ('flow_node', 'Flow node'), ('inbound', 'Inbound')], default='inbound', max_length=16)),
                ('invoked_by', models.CharField(default='system', max_length=128)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=8)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('awaiting_approval', 'Awaiting approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='queued', max_length=32)),
                ('expected_completion_by', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification_result', models.ForeignKey(blank=True, db_column='classification_result_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifier.classificationresult')),
                ('parent_task', models.ForeignKey(blank=True, db_column='parent_task_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'tasks',
                'indexes': [models.Index(fields=['tenant', 'status', 'expected_completion_by'], name='idx_tasks_tenant_status')],
            },
        ),
    ]
