# Generated by Django 4.2.30 on 2026-07-03 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='outputs',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='review_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('edit_light', 'Edit light'), ('rejected', 'Rejected')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
