# Generated by Django 4.2.30 on 2026-07-03 17:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_enable_rls'),
        ('tasks', '0003_task_rls'),
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('edited', 'Edited'), ('rejected', 'Rejected'), ('sent', 'Sent')], max_length=16)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(blank=True, db_column='draft_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='drafts.draft')),
                ('task', models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'outcome_entries',
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='idx_outcome_tenant_created')],
            },
        ),
    ]
