# Generated by Django 4.2.30 on 2026-07-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataclassificationdefault',
            name='default_class',
            field=models.CharField(choices=[('N0', 'N0'), ('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4')], default='N1', max_length=2),
        ),
        migrations.AlterField(
            model_name='dpastatement',
            name='status',
            field=models.CharField(choices=[('missing', 'Missing'), ('signed', 'Signed'), ('blocked', 'Blocked')], default='missing', max_length=16),
        ),
        migrations.AlterField(
            model_name='policyblock',
            name='declared_class',
            field=models.CharField(choices=[('N0', 'N0'), ('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4')], max_length=2),
        ),
        migrations.AlterField(
            model_name='policyblock',
            name='effective_class',
            field=models.CharField(choices=[('N0', 'N0'), ('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4')], max_length=2),
        ),
    ]
