# Generated by Django 4.2.30 on 2026-07-03 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_task_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_approval', 'Awaiting approval'), ('approved', 'Approved'), ('edited', 'Edited'), ('rejected', 'Rejected'), ('sent', 'Sent'), ('expired', 'Expired'), ('approved_pending_send', 'Approved pending send')], default='pending', max_length=32)),
                ('original_content', models.JSONField(default=dict)),
                ('edited_content', models.JSONField(blank=True, null=True)),
                ('edit_reason', models.TextField(blank=True, default='')),
                ('edit_classification', models.CharField(blank=True, choices=[('tone', 'Tone'), ('data', 'Data'), ('structure', 'Structure'), ('policy', 'Policy'), ('scope', 'Scope'), ('context', 'Context')], max_length=16, null=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=16)),
                ('recipient', models.CharField(blank=True, default='', max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, db_column='approver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drafts',
            },
        ),
        migrations.CreateModel(
            name='EvidenceBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bundle_json', models.JSONField(default=dict)),
                ('bundle_hash', models.CharField(max_length=64)),
                ('client_view', models.JSONField(default=dict)),
                ('internal_view', models.JSONField(default=dict)),
                ('privacy_classification', models.CharField(default='N2', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(blank=True, db_column='draft_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_bundles', to='drafts.draft')),
                ('task', models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_bundles', to='tasks.task')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'evidence_bundles',
            },
        ),
        migrations.AddField(
            model_name='draft',
            name='evidence_bundle',
            field=models.ForeignKey(blank=True, db_column='evidence_bundle_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='drafts.evidencebundle'),
        ),
        migrations.AddField(
            model_name='draft',
            name='task',
            field=models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='draft',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='OscillationCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=255)),
                ('consecutive_clean_approvals', models.IntegerField(default=0)),
                ('last_reset_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oscillation_counters',
                'unique_together': {('tenant', 'user', 'agent_id')},
            },
        ),
        migrations.AddIndex(
            model_name='evidencebundle',
            index=models.Index(fields=['draft'], name='idx_evidence_bundles_draft'),
        ),
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['tenant', 'status', 'expires_at'], name='idx_drafts_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['task'], name='idx_drafts_task'),
        ),
    ]
