# Generated by Django 4.2.30 on 2026-07-03 01:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=16)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('data_class', models.CharField(choices=[('N0', 'N0'), ('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4')], default='N1', max_length=2)),
                ('status', models.CharField(choices=[('received', 'Received'), ('classifying', 'Classifying'), ('classified', 'Classified'), ('pending_human_review', 'Pending human review'), ('routed_to_task', 'Routed to task'), ('archived', 'Archived'), ('failed', 'Failed'), ('manual_review', 'Manual review')], default='received', max_length=32)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'feed_items',
            },
        ),
        migrations.CreateModel(
            name='ClassifierSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('origin', models.CharField(default='system', max_length=16)),
                ('prompt_template', models.TextField()),
                ('output_schema', models.JSONField(default=dict)),
                ('threshold', models.DecimalField(decimal_places=3, default=0.85, max_digits=4)),
                ('model_id', models.CharField(default='anthropic/claude-3-5-haiku-20241022', max_length=128)),
                ('timeout_ms', models.IntegerField(default=10000)),
                ('cost_cap_usd', models.DecimalField(decimal_places=4, default=0.05, max_digits=8)),
                ('status', models.CharField(choices=[('shadow', 'Shadow'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='active', max_length=16)),
                ('active_version', models.CharField(default='1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'classifier_skills',
            },
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_context', models.JSONField(default=dict)),
                ('features', models.JSONField(default=dict)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('routing_zone', models.CharField(default='zone_4', max_length=16)),
                ('status', models.CharField(choices=[('classified', 'Classified'), ('pending_human_review', 'Pending human review'), ('routed_to_task', 'Routed to task'), ('failed', 'Failed')], default='classified', max_length=32)),
                ('model_id', models.CharField(blank=True, max_length=128, null=True)),
                ('model_version', models.CharField(blank=True, max_length=32, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classifier_skill', models.ForeignKey(db_column='classifier_skill_id', on_delete=django.db.models.deletion.RESTRICT, to='classifier.classifierskill')),
                ('feed_item', models.ForeignKey(db_column='feed_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='classification_results', to='classifier.feeditem')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'classification_results',
            },
        ),
        migrations.CreateModel(
            name='Tier0Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pattern', models.JSONField(default=dict)),
                ('priority', models.IntegerField(default=0)),
                ('action_context', models.JSONField(default=dict)),
                ('origin', models.CharField(default='system', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'tier0_rules',
                'indexes': [models.Index(fields=['tenant', 'priority'], name='idx_t0_rules_tenant_priority')],
            },
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['tenant', 'status', 'received_at'], name='idx_feed_items_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='classificationresult',
            index=models.Index(fields=['feed_item'], name='idx_clsresult_feed_item'),
        ),
    ]
