#!/usr/bin/env python3
"""SQLite → PostgreSQL migration helper for FaberLoom E3-1.

This script copies the contents of a FaberLoom SQLite database into a target
PostgreSQL schema. It is intentionally standalone: it introspects the SQLite
schema dynamically so it does not need to be updated every time a new migration
is added. ``psycopg`` (v3) is preferred; ``psycopg2`` is used as a fallback.

Usage:
    # Planificación sin conexión
    python sqlite_to_postgres.py --sqlite-path /data/faberloom.sqlite3 \
        --postgres-url postgresql://user:pass@localhost:5435/faberloom \
        --dry-run

    # Ejecución productiva
    python sqlite_to_postgres.py --sqlite-path /data/faberloom.sqlite3 \
        --postgres-url postgresql://user:pass@localhost:5435/faberloom \
        --schema public --drop-existing \
        --log-path migration.jsonl

    # Migración con campos JSON como TEXT en lugar de JSONB
    python sqlite_to_postgres.py --sqlite-path /data/faberloom.sqlite3 \
        --postgres-url postgresql://user:pass@localhost:5435/faberloom \
        --json-as-text
"""

from __future__ import annotations

import argparse
import json
import os
import sqlite3
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


# SQLite stores column type declarations as free text. We normalise the most
# common variants to a small set of Postgres-friendly types.
_SQLITE_TO_POSTGRES_TYPE: dict[str, str] = {
    "TEXT": "TEXT",
    "CHAR": "TEXT",
    "VARCHAR": "TEXT",
    "NVARCHAR": "TEXT",
    "CLOB": "TEXT",
    "STRING": "TEXT",
    "INTEGER": "INTEGER",
    "INT": "INTEGER",
    "BIGINT": "BIGINT",
    "SMALLINT": "SMALLINT",
    "TINYINT": "SMALLINT",
    "BOOLEAN": "BOOLEAN",
    "REAL": "REAL",
    "FLOAT": "REAL",
    "DOUBLE": "DOUBLE PRECISION",
    "NUMERIC": "NUMERIC",
    "DECIMAL": "NUMERIC",
    "BLOB": "BYTEA",
    "BINARY": "BYTEA",
    "VARBINARY": "BYTEA",
    "DATETIME": "TIMESTAMPTZ",
    "TIMESTAMP": "TIMESTAMPTZ",
    "DATE": "DATE",
    "JSON": "JSONB",
    "JSONB": "JSONB",
}

# Tables generated by SQLite that are never migrated. Virtual/temporary tables
# and metadata-only tables that either do not exist in Postgres or are rebuilt
# by the application are excluded explicitly.
_IGNORED_SQLITE_TABLES = {
    "sqlite_sequence",
    "sqlite_stat1",
    "sqlite_stat2",
    "sqlite_stat3",
    "sqlite_stat4",
    "_workspace_seal_backup",
    "_editorial_history_v13",
    "_workspace_smtp_config_v18",
}

# FTS5 creates shadow tables with the same prefix as the virtual table.
_IGNORED_SQLITE_PREFIXES = (
    "kb_chunk_fts",
)


def _is_ignored_sqlite_table(name: str) -> bool:
    return name in _IGNORED_SQLITE_TABLES or name.startswith(_IGNORED_SQLITE_PREFIXES)


@dataclass
class ColumnDef:
    name: str
    sqlite_type: str
    notnull: bool
    default_value: Any
    primary_key: bool


@dataclass
class IndexDef:
    name: str
    table: str
    unique: bool
    columns: list[str]


@dataclass
class TablePlan:
    name: str
    columns: list[ColumnDef]
    row_count: int
    primary_keys: list[str]
    foreign_keys: list[dict[str, Any]] = field(default_factory=list)
    indexes: list[IndexDef] = field(default_factory=list)
    unique_constraints: list[IndexDef] = field(default_factory=list)


@dataclass
class TableResult:
    name: str
    source_rows: int
    dest_rows: int
    duration_s: float
    error: str | None = None


class MigrationError(Exception):
    """Recoverable migration error reported per table."""


def _normalize_sqlite_type(
    declared: str, json_as_text: bool = False, col_name: str | None = None
) -> str:
    """Return a Postgres type from a SQLite type declaration.

    When ``json_as_text`` is False, columns whose names end with ``_json`` are
    mapped to JSONB because SQLite stores them as TEXT but the application
    always writes valid JSON. This keeps Postgres indexes and JSON operators
    available while preserving the TEXT fallback via ``--json-as-text``.
    """

    tokens = declared.upper().split("(")[0].split()
    pg_type: str | None = None
    for token in tokens:
        candidate = _SQLITE_TO_POSTGRES_TYPE.get(token)
        if candidate:
            pg_type = candidate
            break

    if pg_type is None:
        pg_type = "TEXT"

    if json_as_text:
        if pg_type == "JSONB":
            return "TEXT"
        return pg_type

    if pg_type == "TEXT" and col_name is not None and col_name.endswith("_json"):
        return "JSONB"

    return pg_type


def _quote_identifier(name: str) -> str:
    """Double-quote a Postgres identifier."""

    return '"' + name.replace('"', '""') + '"'


def _format_default(value: Any, pg_type: str) -> str | None:
    """Translate a SQLite PRAGMA default value to a Postgres literal."""

    if value is None:
        return None
    if isinstance(value, str):
        stripped = value.strip()
        upper = stripped.upper()
        if upper in ("CURRENT_TIMESTAMP", "CURRENT_TIME", "CURRENT_DATE"):
            return upper
        if upper in ("NULL",):
            return None
        # SQLite stores string defaults with single quotes already included.
        if stripped.startswith("'") and stripped.endswith("'"):
            inner = stripped[1:-1].replace("''", "'")
            return "'" + inner.replace("'", "''") + "'"
        # Numeric / boolean literals encoded as strings.
        if pg_type in (
            "INTEGER",
            "BIGINT",
            "SMALLINT",
            "REAL",
            "DOUBLE PRECISION",
            "NUMERIC",
            "BOOLEAN",
        ):
            if upper in ("TRUE", "FALSE"):
                return upper
            try:
                float(stripped)
                return stripped
            except ValueError:
                pass
        return "'" + stripped.replace("'", "''") + "'"
    return str(value)


# SQLite internal FTS5 shadow tables.
_FTS_SHADOW_SUFFIXES = ("_fts", "_fts_idx", "_fts_data", "_fts_docsize", "_fts_config", "_fts_content")


def _is_fts_shadow(name: str) -> bool:
    return any(name.endswith(suffix) for suffix in _FTS_SHADOW_SUFFIXES)


def _sqlite_table_names(conn: sqlite3.Connection) -> list[str]:
    """Return user-defined table names in creation order (sin shadows FTS5)."""

    cursor = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY rowid"
    )
    return [row[0] for row in cursor.fetchall() if not _is_fts_shadow(row[0])]


def _load_table_plan(conn: sqlite3.Connection, table_name: str) -> TablePlan:
    """Build a migration plan for one SQLite table."""

    columns: list[ColumnDef] = []
    primary_keys: list[str] = []
    for row in conn.execute(f'PRAGMA table_info("{table_name}")'):
        cid, name, ctype, notnull, default_value, pk = row
        col = ColumnDef(
            name=name,
            sqlite_type=ctype or "TEXT",
            notnull=bool(notnull),
            default_value=default_value,
            primary_key=bool(pk),
        )
        columns.append(col)
        if pk:
            primary_keys.append(name)

    # Row count
    row_count = conn.execute(f'SELECT COUNT(*) FROM "{table_name}"').fetchone()[0]

    # Foreign keys
    foreign_keys: list[dict[str, Any]] = []
    try:
        for row in conn.execute(f'PRAGMA foreign_key_list("{table_name}")'):
            foreign_keys.append(
                {
                    "id": row[0],
                    "seq": row[1],
                    "table": row[2],
                    "from": row[3],
                    "to": row[4],
                    "on_update": row[5],
                    "on_delete": row[6],
                    "match": row[7],
                }
            )
    except sqlite3.Error:
        foreign_keys = []

    # Indexes and unique constraints. SQLite's PRAGMA index_list returns an
    # ``origin`` column since 3.30: 'c' for CREATE INDEX, 'u' for UNIQUE
    # constraints, and 'pk' for primary keys. We recreate UNIQUE constraints as
    # unique indexes so Postgres enforces them as well.
    indexes: list[IndexDef] = []
    unique_constraints: list[IndexDef] = []
    try:
        for idx_row in conn.execute(f'PRAGMA index_list("{table_name}")'):
            idx_name = idx_row[1]
            unique = bool(idx_row[2])
            origin = idx_row[3] if len(idx_row) > 3 else None
            if idx_name.startswith("sqlite_autoindex_"):
                if origin == "u" and unique:
                    idx_cols: list[str] = []
                    for idx_info in conn.execute(f'PRAGMA index_info("{idx_name}")'):
                        idx_cols.append(idx_info[2])
                    if idx_cols:
                        unique_constraints.append(
                            IndexDef(
                                name=idx_name,
                                table=table_name,
                                unique=True,
                                columns=idx_cols,
                            )
                        )
                # pk autoindexes are already represented by the PRIMARY KEY.
                continue
            idx_cols = []
            for idx_info in conn.execute(f'PRAGMA index_info("{idx_name}")'):
                idx_cols.append(idx_info[2])
            if idx_cols:
                indexes.append(
                    IndexDef(
                        name=idx_name,
                        table=table_name,
                        unique=unique,
                        columns=idx_cols,
                    )
                )
    except sqlite3.Error:
        pass

    return TablePlan(
        name=table_name,
        columns=columns,
        row_count=row_count,
        primary_keys=primary_keys,
        foreign_keys=foreign_keys,
        indexes=indexes,
        unique_constraints=unique_constraints,
    )


def _build_create_table_sql(
    plan: TablePlan, schema: str, json_as_text: bool = False
) -> str:
    """Generate a Postgres CREATE TABLE statement from a table plan."""

    parts: list[str] = []
    for col in plan.columns:
        pg_type = _normalize_sqlite_type(
            col.sqlite_type, json_as_text=json_as_text, col_name=col.name
        )
        decl = f"{_quote_identifier(col.name)} {pg_type}"
        single_pk = col.primary_key and len(plan.primary_keys) == 1
        if single_pk and pg_type == "INTEGER":
            # SQLite INTEGER PRIMARY KEY is an alias for the rowid. In Postgres
            # we model it as a generated identity so behaviour stays close, but
            # BY DEFAULT so existing rowid values can be migrated verbatim.
            decl = f"{_quote_identifier(col.name)} INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        elif single_pk:
            decl += " PRIMARY KEY"
        if col.notnull and not single_pk:
            decl += " NOT NULL"
        default = _format_default(col.default_value, pg_type)
        if default is not None:
            decl += f" DEFAULT {default}"
        parts.append("    " + decl)

    # Composite primary keys (when no single column was marked pk=1 but a
    # sqlite_autoindex unique PK index exists, we still want to reproduce it).
    if len(plan.primary_keys) > 1:
        pk_cols = ", ".join(_quote_identifier(c) for c in plan.primary_keys)
        parts.append(f"    PRIMARY KEY ({pk_cols})")

    # Foreign keys. We keep them deferred to avoid ordering issues during load.
    # El audit trail es append-only e inmutable: conserva referencias a
    # workspaces ya borrados, así que no lleva FKs (huérfanos legítimos).
    fk_exempt = plan.name in {"audit_log", "_workspace_seal_backup"}
    for fk in ([] if fk_exempt else plan.foreign_keys):
        from_col = _quote_identifier(fk["from"])
        to_table = _quote_identifier(fk["table"])
        to_col = _quote_identifier(fk["to"])
        on_update = fk.get("on_update", "NO ACTION").upper()
        on_delete = fk.get("on_delete", "NO ACTION").upper()
        parts.append(
            f"    FOREIGN KEY ({from_col}) REFERENCES {schema}.{to_table}({to_col})"
            f" ON UPDATE {on_update} ON DELETE {on_delete} DEFERRABLE INITIALLY DEFERRED"
        )

    table_quoted = _quote_identifier(plan.name)
    schema_quoted = _quote_identifier(schema)
    return f"CREATE TABLE {schema_quoted}.{table_quoted} (\n" + ",\n".join(parts) + "\n)"


def _build_create_index_sql(index: IndexDef, schema: str) -> str:
    """Generate a Postgres CREATE INDEX statement."""

    idx_quoted = _quote_identifier(index.name)
    schema_quoted = _quote_identifier(schema)
    table_quoted = _quote_identifier(index.table)
    cols = ", ".join(_quote_identifier(c) for c in index.columns)
    unique = "UNIQUE " if index.unique else ""
    return f"CREATE {unique}INDEX IF NOT EXISTS {idx_quoted} ON {schema_quoted}.{table_quoted} ({cols})"


def _build_insert_sql(plan: TablePlan, schema: str) -> tuple[str, int]:
    """Return a reusable INSERT template and the number of placeholders per row."""

    table_quoted = _quote_identifier(plan.name)
    schema_quoted = _quote_identifier(schema)
    cols = ", ".join(_quote_identifier(c.name) for c in plan.columns)
    placeholders = ", ".join(["%s"] * len(plan.columns))
    single = f"INSERT INTO {schema_quoted}.{table_quoted} ({cols}) VALUES ({placeholders})"
    return single, len(plan.columns)


def _log(log_path: Path | None, entry: dict[str, Any]) -> None:
    """Append a JSONL record if a log path is configured."""

    if log_path is None:
        return
    with log_path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(entry, ensure_ascii=False, default=str) + "\n")


def _connect_postgres(postgres_url: str):
    """Import a psycopg driver lazily and return a connection.

    ``psycopg`` (PostgreSQL driver v3) is preferred; ``psycopg2`` is accepted as
    a fallback so the script runs in older environments.
    """

    errors: list[str] = []
    for module_name in ("psycopg", "psycopg2"):
        try:
            mod = __import__(module_name)
            conn = mod.connect(postgres_url)
            conn.autocommit = False
            return conn
        except ImportError as exc:
            errors.append(f"{module_name}: {exc}")
            continue

    raise RuntimeError(
        "No PostgreSQL driver found. Install psycopg (v3) or psycopg2. "
        + " ".join(errors)
    )


def _migrate_table(
    sqlite_conn: sqlite3.Connection,
    pg_conn,
    plan: TablePlan,
    schema: str,
    batch_size: int,
    log_path: Path | None,
) -> TableResult:
    """Migrate a single table inside a Postgres transaction."""

    start = time.perf_counter()
    table_quoted = _quote_identifier(plan.name)
    schema_quoted = _quote_identifier(schema)
    cursor = pg_conn.cursor()

    try:
        # Truncate/reload pattern inside the per-table transaction.
        cursor.execute(f"DELETE FROM {schema_quoted}.{table_quoted}")

        insert_sql, _ = _build_insert_sql(plan, schema)

        # Stream rows to keep memory bounded even on large tables.
        batch: list[tuple[Any, ...]] = []
        for row in sqlite_conn.execute(f'SELECT * FROM "{plan.name}"'):
            batch.append(tuple(row))
            if len(batch) >= batch_size:
                cursor.executemany(insert_sql, batch)
                batch.clear()
        if batch:
            cursor.executemany(insert_sql, batch)
            batch.clear()

        pg_conn.commit()

        cursor.execute(f"SELECT COUNT(*) FROM {schema_quoted}.{table_quoted}")
        dest_rows = cursor.fetchone()[0]
        duration = time.perf_counter() - start
        result = TableResult(
            name=plan.name,
            source_rows=plan.row_count,
            dest_rows=dest_rows,
            duration_s=duration,
        )
        _log(
            log_path,
            {
                "table": plan.name,
                "source_rows": plan.row_count,
                "dest_rows": dest_rows,
                "duration_s": round(duration, 3),
                "status": "ok" if dest_rows == plan.row_count else "mismatch",
                "error": None,
            },
        )
        return result
    except Exception as exc:
        pg_conn.rollback()
        duration = time.perf_counter() - start
        _log(
            log_path,
            {
                "table": plan.name,
                "source_rows": plan.row_count,
                "dest_rows": 0,
                "duration_s": round(duration, 3),
                "status": "error",
                "error": str(exc),
            },
        )
        return TableResult(
            name=plan.name,
            source_rows=plan.row_count,
            dest_rows=0,
            duration_s=duration,
            error=str(exc),
        )
    finally:
        cursor.close()


def _create_schema_if_missing(pg_conn, schema: str) -> None:
    """Ensure the target schema exists."""

    cursor = pg_conn.cursor()
    cursor.execute(f"CREATE SCHEMA IF NOT EXISTS {_quote_identifier(schema)}")
    pg_conn.commit()
    cursor.close()


def _drop_table_if_exists(pg_conn, table_name: str, schema: str) -> None:
    """Drop dependent objects for a table to allow re-runs."""

    cursor = pg_conn.cursor()
    schema_quoted = _quote_identifier(schema)
    table_quoted = _quote_identifier(table_name)
    cursor.execute(f"DROP TABLE IF EXISTS {schema_quoted}.{table_quoted} CASCADE")
    pg_conn.commit()
    cursor.close()


def _create_fts_gin_index(pg_conn, schema: str) -> None:
    """Create a GIN index to replace SQLite's FTS5 kb_chunk_fts table."""

    cursor = pg_conn.cursor()
    schema_quoted = _quote_identifier(schema)
    try:
        # The application can query with to_tsvector('simple', content_text).
        cursor.execute(
            f"""
            CREATE INDEX IF NOT EXISTS {schema_quoted}.ix_kb_chunk_content_tsvector
            ON {schema_quoted}.kb_chunk USING GIN (to_tsvector('simple', content_text))
            """
        )
        pg_conn.commit()
    except Exception:
        pg_conn.rollback()
        raise
    finally:
        cursor.close()


def _vacuum_analyze(pg_conn) -> None:
    """Run VACUUM ANALYZE on the new schema if the driver supports it."""

    # psycopg v3 does not allow VACUUM inside a transaction block. Leave it to
    # the DBA or run it manually after the migration.
    pass


def _migrate(
    sqlite_path: str,
    postgres_url: str,
    *,
    schema: str,
    dry_run: bool,
    drop_existing: bool,
    batch_size: int,
    log_path: Path | None,
    json_as_text: bool,
    fts_gin: bool,
) -> int:
    """Run the migration and return an exit code."""

    if not os.path.exists(sqlite_path):
        print(f"ERROR: SQLite file not found: {sqlite_path}", file=sys.stderr)
        return 1

    sqlite_conn = sqlite3.connect(sqlite_path)
    sqlite_conn.row_factory = sqlite3.Row

    table_names = [
        name
        for name in _sqlite_table_names(sqlite_conn)
        if not _is_ignored_sqlite_table(name)
    ]
    plans = [_load_table_plan(sqlite_conn, name) for name in table_names]

    if dry_run:
        print(f"Dry-run mode: {len(plans)} table(s) found in {sqlite_path}")
        print("-" * 60)
        total_rows = 0
        for plan in plans:
            print(f"\nTable: {plan.name} ({plan.row_count} rows)")
            print(_build_create_table_sql(plan, schema, json_as_text=json_as_text) + ";")
            for idx in plan.indexes:
                print(_build_create_index_sql(idx, schema) + ";")
            for idx in plan.unique_constraints:
                print(_build_create_index_sql(idx, schema) + ";")
            total_rows += plan.row_count
        if fts_gin:
            print(
                f"\nCREATE INDEX IF NOT EXISTS \"{schema}\".\"ix_kb_chunk_content_tsvector\" "
                f'ON "kb_chunk" USING GIN (to_tsvector(\'simple\', content_text));'
            )
        print("-" * 60)
        print(f"Total rows to migrate: {total_rows}")
        print("No Postgres connection was attempted (dry-run).")
        sqlite_conn.close()
        return 0

    pg_conn = _connect_postgres(postgres_url)
    try:
        _create_schema_if_missing(pg_conn, schema)

        if drop_existing:
            for plan in plans:
                _drop_table_if_exists(pg_conn, plan.name, schema)

        # Phase 1: create tables. El orden por rowid de SQLite no garantiza que
        # las FKs apunten a tablas ya creadas, así que se hacen pasadas
        # sucesivas difiriendo las que fallan hasta resolver dependencias.
        print(f"Creating {len(plans)} table(s) in schema '{schema}'...")
        if not drop_existing:
            for plan in plans:
                _drop_table_if_exists(pg_conn, plan.name, schema)

        pending = list(plans)
        for _pass in range(len(plans) + 1):
            if not pending:
                break
            still_pending = []
            last_error: Exception | None = None
            for plan in pending:
                cursor = pg_conn.cursor()
                try:
                    cursor.execute(
                        _build_create_table_sql(plan, schema, json_as_text=json_as_text)
                    )
                    pg_conn.commit()
                except Exception as exc:
                    pg_conn.rollback()
                    still_pending.append(plan)
                    last_error = exc
                finally:
                    cursor.close()
            if len(still_pending) == len(pending):
                raise RuntimeError(
                    f"No progress creating tables; {len(still_pending)} pending. Last error: {last_error}"
                )
            pending = still_pending

        # Phase 2: migrate data.
        results: list[TableResult] = []
        print("Migrating data...")
        for plan in plans:
            result = _migrate_table(
                sqlite_conn, pg_conn, plan, schema, batch_size, log_path
            )
            results.append(result)
            status = (
                "OK"
                if result.error is None and result.dest_rows == result.source_rows
                else "FAIL"
            )
            print(
                f"  [{status}] {result.name}: {result.source_rows} → {result.dest_rows} "
                f"({result.duration_s:.2f}s)"
            )

        # Phase 2.5: sincronizar secuencias identity con el MAX cargado.
        for plan in plans:
            int_pks = [
                c
                for c in plan.columns
                if c.primary_key
                and _normalize_sqlite_type(c.sqlite_type, json_as_text=json_as_text, col_name=c.name)
                == "INTEGER"
            ]
            if len(plan.primary_keys) == 1 and int_pks:
                col = int_pks[0].name
                cursor = pg_conn.cursor()
                try:
                    cursor.execute(
                        f"SELECT setval(pg_get_serial_sequence(%s, %s), COALESCE((SELECT MAX({_quote_identifier(col)}) FROM {_quote_identifier(schema)}.{_quote_identifier(plan.name)}), 0) + 1, false)",
                        (f"{schema}.{plan.name}", col),
                    )
                    pg_conn.commit()
                except Exception:
                    pg_conn.rollback()
                finally:
                    cursor.close()

        # Phase 3: recreate indexes after data load (faster than creating first).
        print("Recreating indexes...")
        for plan in plans:
            for idx in plan.indexes + plan.unique_constraints:
                cursor = pg_conn.cursor()
                try:
                    cursor.execute(_build_create_index_sql(idx, schema))
                    pg_conn.commit()
                except Exception as exc:
                    pg_conn.rollback()
                    print(
                        f"  [WARN] index {idx.name} on {idx.table}: {exc}",
                        file=sys.stderr,
                    )
                finally:
                    cursor.close()

        # Phase 4: create FTS replacement index.
        if fts_gin:
            print("Creating FTS GIN replacement index...")
            try:
                _create_fts_gin_index(pg_conn, schema)
                print("  [OK] ix_kb_chunk_content_tsvector")
            except Exception as exc:
                print(
                    f"  [WARN] could not create FTS GIN index: {exc}",
                    file=sys.stderr,
                )

        # Phase 5: verify counts.
        print("Verifying row counts...")
        mismatches = 0
        for result in results:
            if result.error:
                mismatches += 1
                print(f"  [ERROR] {result.name}: {result.error}", file=sys.stderr)
            elif result.source_rows != result.dest_rows:
                mismatches += 1
                print(
                    f"  [MISMATCH] {result.name}: {result.source_rows} source, "
                    f"{result.dest_rows} dest",
                    file=sys.stderr,
                )
            else:
                print(f"  [OK] {result.name}: {result.dest_rows}")

        if mismatches:
            print(f"\nMigration completed with {mismatches} issue(s).", file=sys.stderr)
            return 2

        print("\nMigration completed successfully.")
        return 0
    finally:
        sqlite_conn.close()
        pg_conn.close()


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""

    parser = argparse.ArgumentParser(
        description="Migrate a FaberLoom SQLite database to PostgreSQL."
    )
    parser.add_argument(
        "--sqlite-path", required=True, help="Path to the source SQLite file."
    )
    parser.add_argument(
        "--postgres-url",
        default="postgresql://localhost/faberloom",
        help="PostgreSQL connection URL.",
    )
    parser.add_argument(
        "--schema", default="public", help="Target Postgres schema (default: public)."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="List tables and DDL without connecting to Postgres.",
    )
    parser.add_argument(
        "--drop-existing",
        action="store_true",
        help="Drop existing target tables before creating them.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=500,
        help="Rows per INSERT batch (default: 500).",
    )
    parser.add_argument("--log-path", help="Optional JSONL log path.")
    parser.add_argument(
        "--json-as-text",
        action="store_true",
        help="Map SQLite JSON columns to TEXT instead of JSONB.",
    )
    parser.add_argument(
        "--no-fts-gin",
        action="store_true",
        dest="no_fts_gin",
        help="Do not create the GIN index that replaces kb_chunk_fts.",
    )
    args = parser.parse_args(argv)

    log_path = Path(args.log_path) if args.log_path else None

    return _migrate(
        sqlite_path=args.sqlite_path,
        postgres_url=args.postgres_url,
        schema=args.schema,
        dry_run=args.dry_run,
        drop_existing=args.drop_existing,
        batch_size=args.batch_size,
        log_path=log_path,
        json_as_text=args.json_as_text,
        fts_gin=not args.no_fts_gin,
    )


if __name__ == "__main__":
    sys.exit(main())
